[package]
name = "hangman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.6.1"
rocket = {version= "^0.5.0-rc.2", features = ["json"]}
serde = "1.0.152"
sorted-vec = "^0.7.0" 
